button_account_page="xpath://span[text()='Giriş Yap']"
button_login_page="id:login"
span_check_login="xpath://span[text()='KEREM ULUSOY']"
span_chart_item_count="id:cartItemCount"
button_shopping_chart="id:shoppingCart"
link_hepsiburada="xpath://a[@title='Hepsiburada']"
link_product_deal_of_the_day="xpath:(//*[contains(@id,'DealOfTheDay')]//a)[3]"
input_product_search="xpath://div[@id='SearchBoxOld']//input"
button_search="xpath://div[text()='ARA']"
label_check_search_is_complete="xpath://label[contains(text(),'Tüm Kategoriler')]"
input_search_brand="xpath://input[@placeholder='Marka ara']"
checkbox_product="brand-jbl"
checkbox_product_price_750_1000="//input[@value='750-1000']"
link_product_color_black="attr-renk-Siyah"
link_first_product_in_search="xpath:(//ul[contains(@class, 'product-list')]//a)[1]"
