button_add_to_chart="id:addToCart"
button_go_to_chart_button="xpath://button[text()='Sepete git']"
link_product_comments="xpath://a[contains(text(),'Değerlendirmeler (')]"
button_review_is_useful="(//div[@class='hermes-ReviewCard-module-tAGUS'])[1]"
span_review_thank_you="xpath://span[text()='Teşekkür Ederiz.']"