channels:
- conda-forge
dependencies:
- ca-certificates=2021.5.30
- libcxx=12.0.1
- libffi=3.3
- ncurses=6.2
- openssl=1.1.1l
- pip=20.1.1
- python=3.7.5
- python_abi=3.7
- readline=8.1
- setuptools=57.4.0
- sqlite=3.36.0
- tk=8.6.11
- wheel=0.37.0
- xz=5.2.5
- zlib=1.2.11
- pip:
  - appdirs==1.4.4
  - attrs==21.2.0
  - Authlib==0.15.4
  - backports.zoneinfo==0.2.1
  - beautifulsoup4==4.9.3
  - cached-property==1.5.2
  - certifi==2021.5.30
  - cffi==1.14.6
  - chardet==3.0.4
  - charset-normalizer==2.0.4
  - click==7.1.2
  - cryptography==3.4.8
  - decorator==5.0.9
  - defusedxml==0.7.1
  - dnspython==2.1.0
  - docutils==0.17.1
  - et-xmlfile==1.1.0
  - exchangelib==3.3.2
  - fpdf2==2.4.3
  - furl==2.1.2
  - graphviz==0.13.2
  - idna==3.2
  - importlib-metadata==4.8.1
  - isodate==0.6.0
  - jsonpath-ng==1.5.3
  - jsonschema==3.2.0
  - lxml==4.6.3
  - mss==6.1.0
  - netsuitesdk==1.24.0
  - notifiers==1.2.1
  - ntlm-auth==1.5.0
  - oauthlib==3.1.1
  - openpyxl==3.0.7
  - orderedmultidict==1.0.1
  - pdfminer.six==20201018
  - Pillow==8.3.2
  - platformdirs==2.3.0
  - ply==3.11
  - proxy-tools==0.1.0
  - pycparser==2.20
  - Pygments==2.10.0
  - pynput-robocorp-fork==3.0.0
  - pyobjc-core==7.3
  - pyobjc-framework-Cocoa==7.3
  - pyobjc-framework-Quartz==7.3
  - pyobjc-framework-WebKit==7.3
  - PyPDF2==1.26.0
  - pyperclip==1.8.2
  - pyrsistent==0.18.0
  - PySocks==1.7.1
  - pytz==2021.1
  - pywebview==3.5
  - requests==2.26.0
  - requests-file==1.5.1
  - requests-ntlm==1.1.0
  - requests-oauthlib==1.3.0
  - requests-toolbelt==0.9.1
  - rfc3987==1.3.8
  - robocorp-dialog==0.2.3
  - robotframework==4.1
  - robotframework-datadriver==1.5.0
  - robotframework-pythonlibcore==2.2.1
  - robotframework-requests==0.7.2
  - robotframework-seleniumlibrary==5.1.3
  - robotframework-seleniumtestability==1.1.0
  - rpaframework==10.3.0
  - rpaframework-core==6.4.0
  - rpaframework-dialogs==0.3.2
  - rpaframework-pdf==0.6.0
  - selenium==3.141.0
  - simple-salesforce==1.11.3
  - six==1.16.0
  - sortedcontainers==2.4.0
  - soupsieve==2.2.1
  - tqdm==4.62.2
  - tweepy==3.10.0
  - typing-extensions==3.10.0.2
  - tzdata==2021.1
  - tzlocal==3.0
  - urllib3==1.26.6
  - webdrivermanager==0.10.0
  - wrapt==1.12.1
  - xlrd==2.0.1
  - xlutils==2.0.0
  - xlwt==1.3.0
  - zeep==4.1.0
  - zipp==3.5.0
